name: Deploy Ecommerce Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            cd /home/ec2-user/E-commerce_Application

            echo "========== Pull Latest Code =========="
            git pull origin main

            echo "========== Build Application =========="
            docker compose -f docker-compose-aws.yml build ecommerce-app

            echo "========== Restart Spring Boot =========="
            docker compose -f docker-compose-aws.yml up -d --no-deps ecommerce-app

            echo "========== Remove Old Images =========="
            docker image prune -f

            echo "========== Running Containers =========="
            docker ps

            echo "========== Deployment Successful =========="